### ISSUE TITLE
A game?  Do you have any screenshots you can share??

### ISSUE THREAD

**Issue by PySimpleGUI** [AberasT/figurace_juego#1]
I'm excited to see "figurace_game" as your repo's name!

![image](https://user-images.githubusercontent.com/46163555/184510022-e4167dd2-b679-4724-b7cf-eebd8b6d7cdb.png)

I would love to see what you've made or are making.  If you have a moment to add a screenshot or two to your readme, I'm sure visitors would love to see as well!

**Comment by AberasT** [comment]
Hi! We made this game as our final project in a course of Python at university :) 
I'll add some screenshots to the readme, thanks for the tip.
PySimpleGUI was recommended by our teachers, great work!

**Comment by PySimpleGUI** [comment]
> PySimpleGUI was recommended by our teachers, great work!

Your teachers are clearly **BRILLIANT**!  Like geniuses!  LOL

![image](https://user-images.githubusercontent.com/46163555/184510438-589b4c1d-9711-4565-94b1-d77e789a8ef4.png)

Can I ask what grade you're in?  I'm thrilled you're using PySimpleGUI while learning to program!

**Comment by AberasT** [comment]
Yes they are! We really enjoyed that course.
We are currently in 2nd grade. It has been very helpful for creating simple GUIs without much effort

**Comment by PySimpleGUI** [comment]
> We really enjoyed that course.

![image](https://user-images.githubusercontent.com/46163555/184510653-4ba644f3-926b-48fc-a2c4-fde56503a68d.png) the enthusiasm you have for programming.  That's so encouraging and motivating for me to see.  FUN.. it's the # 1 goal for PySimpleGUI, so sounds like maybe that goal was met.

**Comment by AberasT** [comment]
It was indeed great fun. Thank you for taking your time to write these words!

**Comment by PySimpleGUI** [comment]
```
MM'"""""`MM MMP"""""YMM MMP"""""""MM M""MMMMMMMM dP dP 
M' .mmm. `M M' .mmm. `M M' .mmmm  MM M  MMMMMMMM 88 88 
M  MMMMMMMM M  MMMMM  M M         `M M  MMMMMMMM 88 88 
M  MMM   `M M  MMMMM  M M  MMMMM  MM M  MMMMMMMM dP dP 
M. `MMM' .M M. `MMM' .M M  MMMMM  MM M  MMMMMMMM       
MM.     .MM MMb     dMM M  MMMMM  MM M         M oo oo 
MMMMMMMMMMM MMMMMMMMMMM MMMMMMMMMMMM MMMMMMMMMMM
```

Nice screenshots!

I had no clue how big or small your project is.

I like how you've made your buttons span the width of the window.  I don't recall seeing that done before the way you've done it doing down your window, with several buttons in a row.

One of the reasons I ask for screenshots and take a particular interest in conversing with students or beginners is that you guys/gals that are still learning are where new ideas come from.  You don't know the limits.  You haven't been taught the "right way" to do things.

> "It took me four years to paint like Raphael, but a lifetime to paint like a child." - Pablo Picasso

I love this quote by Picasso.  It captures how I want to write software... like a child... without limits... willing to try things that haven't been tried.

Thanks for the great conversation and thank you for teaching me a new technique to use in PySimpleGUI windows.  I hope it's OK if I, ahem, borrow your idea.  😉
