### ISSUE TITLE
Alignment suggestion.....

### ISSUE THREAD

**Issue by PySimpleGUI** [AberasT/figurace_juego#2]
I saw in your (AWESOME) screenshots this config window

![image](https://user-images.githubusercontent.com/46163555/184511738-32fcbdbc-fce4-4769-b8f3-80a995a960f8.png)

I would suggest this trick to get your sliders and text to line up...

![image](https://user-images.githubusercontent.com/46163555/184511726-60df6613-1d71-44fa-b011-9670e91bcb3a.png)

What I did was replaced one parameter in your Text elements
```python
justification="center"
```

I changed to
```python
s=30
```

I removed the defaults so that I didn't have to include a lot of other code.  This is what my hacked up bit of code looks like:
```python
    elem_datasets = [sg.Text("Dataset ", font="Helvetica 13", s=30),
                     sg.Combo(nombres_datasets, key="-CONFIG_DATASET-", font="Helvetica 13", s=(18, 1), readonly=True)]

    elem_tiempo = [sg.Text("Tiempo límite por ronda (seg)", s=30, font="Helvetica 13"),
                   sg.Slider(range=(1, 60), key="-CONFIG_TIEMPO-", orientation="h", border_width=10,  font="Helvetica 13",
                             s=(18, 1), enable_events=True)]

    elem_rondas = [sg.Text("Cantidad de rondas por partida", s=30, font="Helvetica 13"),
                   sg.Slider(range=(1, 50), key="-CONFIG_RONDAS-", orientation="h", border_width=10,  font="Helvetica 13",
                             s=(18, 1), enable_events=True)]

    elem_puntos_bien = [sg.Text("Puntos por correcta", font="Helvetica 13", s=30),
                        sg.Slider(range=(1, 100), key="-CONFIG_PUNTOS_BIEN-", orientation="h", border_width=10,
                                  font="Helvetica 13", s=(18, 1), enable_events=True)]

    elem_puntos_mal = [sg.Text("Puntos restados por incorrecta", font="Helvetica 13", s=30),
                       sg.Slider(range=(-1, -100), key="-CONFIG_PUNTOS_MAL-", orientation="h", border_width=10,
                                 font="Helvetica 13", s=(18, 1), enable_events=True)]

    elem_carac_tarjeta = [sg.Text("Características a mostrar por tarjeta", font="Helvetica 13", s=30),
                          sg.Slider(range=(1, 5), key="-CONFIG_CANT_CARAC-", orientation="h", border_width=10,
                                    font="Helvetica 13", s=(18, 1), enable_events=True)]

    elem_botones = [sg.Button("Guardar", key="-CONFIG_GUARDAR-", font="Helvetica 13", s=(10, 1)),
                    sg.Button("Volver", key="-CONFIG_VOLVER-", font="Helvetica 13", s=(10, 1))]

```

**Comment by AberasT** [comment]
That looks great and I just changed it, thanks! I also changed the theme to "DarkBlue". You can see the new screenshots :smirk:

**Comment by PySimpleGUI** [comment]
Ooooooo!

Very nice!

I've never seen Sliders look like yours.  I didn't know they could look like that, to be honest.  They're skinny, but not at the same time.  Very creative of you.  

One of the reasons I like to see screenshots of projects is that it's how I learn new techniques and new ways of using PySimpleGUI that I've not tried before.  As I mentioned, it's where innovation often lies.  I saw buttons spanning the row and sliders that have a unique look in your one project.  Great stuff!  Thanks for sharing with everyone what you've made.
